"""make a new table TaskResultDB

Revision ID: 236da8ffcc77
Revises: 38ba48206a4b
Create Date: 2026-09-24 12:31:00.077433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236da8ffcc77'
down_revision: Union[str, Sequence[str], None] = '38ba48206a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('original_length', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_result_task_id'), 'task_result', ['task_id'], unique=True)
    op.add_column('tasks', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'error')
    op.drop_column('tasks', 'finished_at')
    op.drop_column('tasks', 'started_at')
    op.drop_index(op.f('ix_task_result_task_id'), table_name='task_result')
    op.drop_table('task_result')
    # ### end Alembic commands ###
