"""create new fiels in TaskDB - owner_token and lease_until

Revision ID: 5dbe9e1cbbc4
Revises: fb62bffde35b
Create Date: 2026-10-02 14:50:57.634540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dbe9e1cbbc4'
down_revision: Union[str, Sequence[str], None] = 'fb62bffde35b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('owner_token', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'tasks', ['owner_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_column('tasks', 'lease_until')
    op.drop_column('tasks', 'owner_token')
    # ### end Alembic commands ###
