"""add new status: Cancelling

Revision ID: a1b59d0f7a6c
Revises: ac0bc8727502
Create Date: 2026-10-08 08:24:36.260818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b59d0f7a6c'
down_revision: Union[str, Sequence[str], None] = 'ac0bc8727502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_tasks_status', 'tasks', type_='check', if_exists=True)
    new_values = ["'new'", "'queued'", "'processing'", "'done'", "'error'", "'cancelled'", "'cancelling'"]
    check_clause = "status IN (" + ", ".join(new_values) + ")"
    # ### end Alembic commands ###
    op.create_check_constraint(
        'ck_tasks_status',
        'tasks',
        check_clause
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_tasks_status', 'tasks', type_='check')
    old_values = ["'new'", "'queued'", "'processing'", "'done'", "'error'", "'cancelled'"]
    check_clause = "status IN (" + ", ".join(old_values) + ")"
    op.create_check_constraint(
        'ck_tasks_status',
        'tasks',
        check_clause
    )
    # ### end Alembic commands ###
