"""create new field "run_id" in TaskDB

Revision ID: ac0bc8727502
Revises: 5dbe9e1cbbc4
Create Date: 2026-10-05 06:38:51.678169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0bc8727502'
down_revision: Union[str, Sequence[str], None] = '5dbe9e1cbbc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('run_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'run_id')
    # ### end Alembic commands ###
